
CREATE TABLE information(
    id VARCHAR(50) NOT NULL PRIMARY KEY,
    pw VARCHAR(50) NOT NULL
);
CREATE TABLE board(
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    description VARCHAR(500) NOT NULL,
    user_id VARCHAR(50) NOT NULL,
    created TIMESTAMP   
);